### ISSUE TITLE
Umožnit přidávat více typů k jednomu dokladu

### ISSUE THREAD

**Issue by manulekonecna** [skaut/Skautske-hospodareni#631]
Zadání:
1.  
- [x] vyčlenit Amount z Chit do vlastní enitity `ChitItem` #798
- [x] datová transformace pro rozdělení #798
- [x] zrefaktorovat exporty a formuláře aby používali ChitItem
- [x] ChitItem má obsahovat i vlastní `purpose` (edit 5.5.2019 sinacek) #848
2. 
- [x] zrefaktorovat exporty pro více ChitItem #851
3.
- [x] upravit UI aby umožnovalo přidat podpoložky #855 

---

Z řad hospodářů je velká poptávka po možnosti přidávání dalších položek k jednomu dokladu. Např. že by na konci řádku bylo tlačítko pro přidání položky a tam by se již pouze přidával další typ a částka (ostatní části by zůstali z původního řádku). Rovněž by se potom vygeneroval jen 1 pokladní doklad. 

Aktuální problém je ten, že pokud půjdu nakoupit do většího obchodu Potraviny, materiál, vybavení, tak musím zadávat jako několik dokladů - u všech zadávat vše znovu + i pak samostatně tisknout - nicméně ráda bych si ráda vytiskla jen 1 výdajový pokladní doklad na celkovou sumu dokladu.
