### ISSUE TITLE
Open source

### ISSUE THREAD

**Issue by fmasa** [skaut/Skautske-hospodareni#797]
Bavili jsme se už několikrát se @sinacek, že zvažujeme opensourcování Hospodaření.

Tuhle issue zakládám, ať máme místo, kde řešit, jak by to mělo vypadat a co je třeba do té doby vyřešit, **pokud se nakonec doopravdy rozhodneme touto cestou jít**.

Osobně bych tomu nedával žádnej milestone, ať to nemusíme uspěchávat.

## Proč by to za to stálo:
- Můžeme používat issues i pro hlášení problémů a požadavků uživatelů. Asi nikdy se nedostaneme do situace, že to bude jedinej kanál, protože pro spoustu lidí může být založení Github účtu překážka.
- Můžeme používat nástroje, které jsou free pro OSS projekty, ale placené pro private projekty.
- Víc lidí se může zapojit do vývoje (spíš teoretickej bod - OSS neznamená, že se najednou objeví nějací contributoři)

## Nevýhody
- Bezpečnost
    - nutnost řešit bezpečnostní chyby tak, aby týdny nevisely jako issues na Githubu.
    - musíme zajistit, že není možný dostat z CI env vars přístupy
- Možný nárust počtu issues a víc času potřebného na komunikaci místo vývoje
- Riziko vzniku konkurenčních Hospodaření? :grin: 

# TODO
- [x] Veřejně přístupné buildy ve Werckeru (skryté deploye)
- [x] Kontrola kódu na platné přístupy - všechny přístupy musí být nově jen v CI jako protected 
- [x] Kontrola WIKI na platné přístupy - všechny přístupy musí být nově jen v CI jako protected proměnné
- [x] Kontrola issues, že neobsahují nějaké citlivé údaje
- [x] Výběr licence a přidání do projektu
- [x] Zveřejnění projektu na Githubu
- [x] Přidání odkazu na Github v Hospodaření
- [x] Informace na FB/Slacku
