### ISSUE TITLE
Nový design

### ISSUE THREAD

**Issue by fmasa** [skaut/Skautske-hospodareni#857]
V #757 jsme změnili UI na aktuální Boostrap a obecně novější stack (Yarn, Sass, Webpack, Babel). Ve většině systému však zůstává starý vzhled

(velká část jednotky, akcí a táborů jsou stejné komponenty - buď u nich budou nějakou dobu 2 šablony, nebo tyto 3 musíme upravit dohromady, čemuž bych se rád vyhnul)

### Root
- [x] App:Default:default
- [x] App:Default:about (#1220)
- [x] App:Debugging:default (#1220)
- [ ] App:Tutorial:event
- [ ] App:Tutorial:default
- [ ] App:Tutorial:travelCommand

## Chybové stránky
- [x] App:Error:403
- [x] App:Error:4xx
- [x] App:Error:405
- [x] App:Error:500
- [x] App:Error:404
- [x] App:Error:noUnit
- [x] App:Error:410

### Akce
- [x] EventModule:Default:new
- [x] EventModule:Default:default
- [x] EventModule:Privileges:default
- [x] EventModule:Event:default
- [x] EventModule:Event:logs
- [x] EventModule:Participant:default
- [x] EventModule:Cashbook:default

### Platby
- [x] PaymentModule:Group:edit
- [x] PaymentModule:Group:newGroup
- [x] PaymentModule:Camp:default
- [x] PaymentModule:Camp:newGroup
- [x] PaymentModule:Camp:massAdd
- [x] PaymentModule:Mail:default
- [x] PaymentModule:GroupList:default
- [x] PaymentModule:Journal:default
- [x] PaymentModule:Registration:newGroup
- [x] PaymentModule:Registration:massAdd
- [x] PaymentModule:Event:default
- [x] PaymentModule:Event:newGroup
- [x] PaymentModule:Event:massAdd
- [x] PaymentModule:BankAccounts:new
- [x] PaymentModule:BankAccounts:edit
- [x] PaymentModule:BankAccounts:detail
- [x] PaymentModule:BankAccounts:default
- [x] PaymentModule:Repayment:default
- [x] PaymentModule:Payment:edit
- [x] PaymentModule:Payment:default
- [x] PaymentModule:Payment:massAdd

### Cesťáky
- [x] TravelModule:Default:detail
- [x] TravelModule:Default:default (#959)
- [x] TravelModule:Default:editTravel
- [x] TravelModule:Default:editCommand
- [x] TravelModule:Default:ex.command
- [x] TravelModule:Contract:new
- [x] TravelModule:Contract:ex.contract.old
- [x] TravelModule:Contract:detail
- [x] TravelModule:Contract:default
- [x] TravelModule:Contract:ex.contract.noz
- [x] TravelModule:Vehicle:new
- [x] TravelModule:Vehicle:detail (#908)
- [x] TravelModule:VehicleList:default (#959)
- [x] TravelModule:Command:edit
- [x] TravelModule:Command:default

### Statistiky
- [x] StatisticsModule:Default:default (#1220)

### Tábory
- [x] CampModule:Default:default
- [x] CampModule:Detail:default
- [x] CampModule:Participant:default
- [x] CampModule:Cashbook:default
- [x] CampModule:Budget:default

### Jednotka
- [x] UnitAccountModule:Chit:default
- [x] UnitAccountModule:Cashbook:default
- [x] UnitAccountModule:Cashbook:noCashbook
- [x] UnitAccountModule:Budget:default
- [x] UnitAccountModule:Budget:add

**Comment by fmasa** [comment]
@sinacek Bude. Asi lepší je nejdřív převést všechny ostatní stránky z Táborů/Akcí/Jednotek a pak v jednom PR převést evidenci plateb.

**Comment by sinacek** [comment]
tutoriály už tu nejsou, takže uzavírám
